services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=logistica'
      - 'POSTGRES_PASSWORD=Administrador01#'
      - 'POSTGRES_USER=postgres'
    ports:
      - '61880:5432'
